In [2]:
import numpy as np

In [4]:
# Basic Array Operations

array = np.random.randint(0, 11, (3, 3))
print("3x3 Array:\n", array)
print("Sum:", np.sum(array))
print("Mean:", np.mean(array))
print("Standard Deviation:", np.std(array))


3x3 Array:
 [[1 8 3]
 [6 5 3]
 [9 0 4]]
Sum: 39
Mean: 4.333333333333333
Standard Deviation: 2.8284271247461903


In [6]:
array_1 = np.random.randint(1, 10, 10)
print("1D Array:", array_1)
print("Cumulative Sum:", np.cumsum(array_1))


1D Array: [6 6 9 8 9 4 8 4 7 6]
Cumulative Sum: [ 6 12 21 29 38 42 50 54 61 67]


In [7]:
array_2_a = np.random.randint(1, 10, (2, 3))
array_2_b = np.random.randint(1, 10, (2, 3))
print("Addition of two arrays:\n", array_2_a + array_2_b)
print("Subtraction of two arrays:\n", array_2_a - array_2_b)
print("Multiplication of two arrays:\n", array_2_a * array_2_b)
print("Division of two arrays:\n", array_2_a / array_2_b)

Addition of two arrays:
 [[16 13 10]
 [ 7  6 15]]
Subtraction of two arrays:
 [[-2 -3  4]
 [-3  4 -3]]
Multiplication of two arrays:
 [[63 40 21]
 [10  5 54]]
Division of two arrays:
 [[0.77777778 0.625      2.33333333]
 [0.4        5.         0.66666667]]


In [8]:
identity_matrix = np.eye(4)
print("4x4 Identity Matrix:\n", identity_matrix)


4x4 Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [10]:
a = np.array([23, 46, 92, 180, 30])
print("Divided Array:", a / 5)


Divided Array: [ 4.6  9.2 18.4 36.   6. ]


In [11]:
# Array Manipulation
array_1D_12 = np.arange(12)
matrix_3x4 = array_1D_12.reshape(3, 4)
print("Reshaped 3x4 Matrix:\n", matrix_3x4)


Reshaped 3x4 Matrix:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [12]:
matrix_3x3 = np.random.randint(1, 10, (3, 3))
print("Flattened Array:", matrix_3x3.flatten())


Flattened Array: [4 7 1 3 7 5 6 2 5]


In [13]:
matrix_3x3_A = np.random.randint(1, 10, (3, 3))
print("Horizontally Stacked:\n", np.hstack((matrix_3x3, matrix_3x3_A)))
print("Vertically Stacked:\n", np.vstack((matrix_3x3, matrix_3x3_A)))


Horizontally Stacked:
 [[4 7 1 2 4 1]
 [3 7 5 6 9 3]
 [6 2 5 8 3 2]]
Vertically Stacked:
 [[4 7 1]
 [3 7 5]
 [6 2 5]
 [2 4 1]
 [6 9 3]
 [8 3 2]]


In [14]:
array_a = np.random.randint(1, 10, (3, 3))
array_b = np.random.randint(1, 10, (3, 2))
concatenated = np.concatenate((array_a, array_b), axis=1)
print("Concatenated Along New Axis:\n", concatenated)

Concatenated Along New Axis:
 [[8 9 2 8 7]
 [9 8 8 1 1]
 [8 7 4 2 6]]


In [15]:
matrix_3x2 = np.random.randint(1, 10, (3, 2))
print("Transposed and Reshaped:\n", matrix_3x2.T.reshape(3, 2))

Transposed and Reshaped:
 [[6 8]
 [2 6]
 [8 9]]


In [16]:
# Indexing and Slicing
array_15 = np.arange(15)
print("Extracted Elements:", array_15[2:10:2])

Extracted Elements: [2 4 6 8]
